Rework exclusion handling to publish metrics
gcovr/gcovr pull request #1016
Opened 2024-10-29 17:31 UTC by dlegaultbbry

- Added excluded flags to some coverage metrics
- Changed code to set the flag instead of wiping things for branches, calls and conditions
- Adjusted reporting code to ignore now present but excluded items

Ran all docker tests, a few reference files were updated from the changes.

#988

2024-10-29 20:28 UTC, Spacetown requested changes
I think this PR should not affect any reference data because only the information is preserved and should be ignored for the report.

2024-10-29 20:28 UTC, Spacetown commented on gcovr/coverage.py
> +        excluded: Optional[bool] = None,
Use always a default value `False` (same as for `LineCoverage`).

2024-10-29 20:28 UTC, Spacetown commented on gcovr/coverage.py
> +        excluded: Optional[bool] = None,
Also default of `False`.

2024-10-29 20:28 UTC, Spacetown commented on gcovr/coverage.py
I would use the same functions as for the line coverage to the other coverage types:
```python
    @property
    def is_excluded(self) -> bool:
        """Return True if the line is excluded."""
        return self.excluded

    @property
    def is_reportable(self) -> bool:
        """Return True if the line is reportable."""
        return not self.excluded

    @property
    def is_covered(self) -> bool:
        """Return True if the line is covered."""
        return self.is_reportable and self.xxx

    @property
    def is_uncovered(self) -> bool:
        """Return True if the line is uncovered."""
        return self.is_reportable and not self.xxx
```

2024-10-29 20:28 UTC, Spacetown commented on tests/excl-branch/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
> +      <td class="linecount partialCoveredLine">1</td>
Why is this changed? I think this change shouldn't affect the reference files.

2024-10-29 20:28 UTC, Spacetown commented on CHANGELOG.rst
> +- Rework exclusion handling to allow publishing metrics (:issue:`1016`)
```suggestion
- Rework exclusion handling to keep information about excluded coverage. (:issue:`1016`)
```

2024-10-30 12:30 UTC, Spacetown commented on gcovr/exclusions/__init__.py
> +                    linecov.exclude()
Than I suggest to exclude only branches and do the other things with the next PR.

2024-10-30 17:59 UTC, dlegaultbbry commented
I'd propose we discuss the behavior before approving and doing the rest.

If I exclude a line, does that mean all branches, calls and conditions under it should report 0 as if never executed? This is what was happening earlier with the first patch set. Right now they are wiped from existence so the metrics never report them because they are deleted before the coverage output is produced. 

There is a slight inconsistency with calls and conditions are they are not emptied out like branches when the line is excluded. This happens in `remove_internal_functions` and `apply_exclusion_ranges`. Maybe it would be better to fix this inconsistency before making other changes to reduce the complexity of reviewing test diff changes.

2024-10-30 21:46 UTC, Spacetown commented
I think it's better to fix the inconsistency first by also clearing the data and then continue on this PR which then shouldn't affect the test data.

2024-11-01 21:29 UTC, Spacetown reviewed
LGFM except the change in the noxfile.

2024-11-01 21:30 UTC, Spacetown approved these changes

2024-11-01 23:14 UTC, dlegaultbbry commented on noxfile.py
> +    session.run("gcovr", "--version")
Wanted to see the gcovr version used printed when running tests. I found it useful, but I can revert the change.

2024-11-02 10:29 UTC, Spacetown commented on noxfile.py
> +    session.run("gcovr", "--version")
GCOVR is installed editable in the virtual environment, no need to print the version.

2024-11-02 10:32 UTC, Spacetown commented on noxfile.py
> +    session.run("gcovr", "--version")
```suggestion
```

2024-11-02 11:06 UTC, merged