Fix filtering wrong path for gcov file
gcovr/gcovr pull request #789
Opened 2023-05-30 09:55 UTC by ukyouz

In Windows, the path include Disk Drive letter in the begining, which was error prone. And thus can not generate any coverage report as described in #769. This changes fix the issue.

* also fix bugs when source file may comes from different Disk Drive.

2023-05-30 11:05 UTC, Spacetown requested changes
Source files coming from different drives seems to be a bug in the project setup. A project should always use one drive, the only thing coming from a different drive should be the compiler.

2023-05-30 11:05 UTC, Spacetown commented on gcovr/formats/html/write.py
> +            realpath(cdata_fname)
Now always absolute paths are displayed instead it relative paths to the root directory.

2023-05-30 11:05 UTC, Spacetown commented on gcovr/formats/gcov/read.py
> +        gcda_fname, options.filter, options.exclude
The filter must use the source file and not the file name of the coverage data.

2023-05-30 11:11 UTC, Spacetown commented
I think the linked issue is wrong. The linked one is related to the example script and gcc-8 on Ubuntu.

2023-05-30 13:01 UTC, ukyouz commented
My original issue is that, there is **no coverage report after running gcovr** command. Maybe the patch is not correct, but I can get all the coverage report as I expected with such fix. Yay I also got the report from compiler sources, that is why I need to handle the disk drive issue.

I think somehow the default filter just **filters out** all the results, that is why I got nothing. I will consider the comment above and re-debug again with my project setup and fix the filter issue.

2023-05-31 03:10 UTC, ukyouz commented
Sure, I opened a issue at #790.

2023-06-01 02:57 UTC, closed without merging