Setup test case for coexisting object directories
gcovr/gcovr pull request #832
Opened 2023-09-21 12:51 UTC by oleurodecision

The PR aims to present a basic setup for testing issue(s) related to coexisting object directories.

The _candidate_tests.bash_ script contains several valid or failing gcovr call variants (parallelised or non-parallelised calls).

Related to #756.

Please ask for any piece of information needed on the subject.

2023-09-21 20:08 UTC, Spacetown commented
Thanks for the test. Please can you use the extension `.cpp` instead of `. cc` to be aligned to the other tests?

2023-09-22 07:32 UTC, oleurodecision commented
My bad! Twenty years of habits ;)

2023-09-22 19:56 UTC, Spacetown requested changes

2023-09-22 19:56 UTC, Spacetown commented on gcovr/tests/test_gcovr.py
> +RE_HTML_HEADER_DATE = re.compile(r"(<td)>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d(\+\d\d:\d\d)?<(/td>)")
Use non captured group for better performance:
```suggestion
RE_HTML_HEADER_DATE = re.compile(r"(<td)>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d(?:\+\d\d:\d\d)?<(/td>)")
```

2023-09-22 19:56 UTC, Spacetown commented on gcovr/tests/test_gcovr.py
> +    contents = RE_HTML_HEADER_DATE.sub("\\1>0000-00-00 00:00:00<\\3", contents)
Offset isn't captured anymore:
```suggestion
    contents = RE_HTML_HEADER_DATE.sub("\\1>0000-00-00 00:00:00<\\2", contents)
```

2023-09-22 19:56 UTC, Spacetown commented on gcovr/tests/coexisting_object_directories/candidate_tests.bash
What's the purpose of this script (it seems not to be called in test)?

Please add a description to the script.

2023-09-22 19:57 UTC, Spacetown commented
Please add a entry in the CHANGELOG.rst.

2023-09-28 07:30 UTC, oleurodecision commented on gcovr/tests/coexisting_object_directories/candidate_tests.bash
The script was added as a reference of failing (and working) cases. The PR only set up what is required for exploring, testing these cases.
Do you want me to add several test cases ? If so, what is the way to do it ? One test folder per case ?

(BTW, thanks for the changelog update, I can only work on the subject on Thursday and Wednesday)

2023-09-29 19:17 UTC, Spacetown commented on gcovr/tests/coexisting_object_directories/candidate_tests.bash
We've one folder per test case but this script is never executed. We only execute the makefiles.

2023-10-19 09:43 UTC, oleurodecision commented on gcovr/tests/coexisting_object_directories/candidate_tests.bash
- script was removed
- dedicated folders were added for each test (the ones described in the removed script)

Thanks waiting for the changes

2023-10-19 20:54 UTC, Spacetown requested changes
I thinkl `gcovr` isn't executed in parallel since the `-j` option is missing when calling make. I`ve adapted the test environment on the branch https://github.com/Spacetown/gcovr/tree/feature/coexisting_object_directories I've modified your tests and the tests coexisting_object_directories-from_build_dir-without_search_dir and coexisting_object_directories-from_root_dir-without_object_dir are failing because of concurency.

Please have a look.

2023-10-20 13:08 UTC, oleurodecision commented
Thanks for upgrading the test environment, this will avoid the dirty call I previously had to do in the makefiles themselves  :disappointed: 

The concurrency issue is now fixed using some dedicated rules (`run.%.done`) to avoid running the same binary several times.

Now (well, at least on my local tests), only the expected tests (the `-without` ones) fail (!)

2023-10-21 07:16 UTC, Spacetown commented
> The concurrency issue is now fixed using some dedicated rules (`run.%.done`) to avoid running the same binary several times.

I don't get what this additional rule is fixing. The result should be the same. I need to check this the next days.

2023-10-23 19:24 UTC, Spacetown commented
The additional rule doesn't change anything. If I understand you correct the tests "without" should fail because of the parallel execution. This we can't test here. For the test `coexisting_object_directories-from_root_dir-without_search_dir` there is a workaround with `GCOV_STRIP` and  `GCOVR_PREFIX`.

2023-10-31 22:57 UTC, Spacetown approved these changes
I've updated the tests to get them green.

@oleurodecision Please can you check again from your side?

2023-11-22 11:36 UTC, Spacetown commented
@oleurodecision Have you already checked it?

2023-12-13 20:12 UTC, Spacetown commented
@oleurodecision I'm waiting for your response to merge this.

2023-12-15 07:51 UTC, oleurodecision commented
Thanks for waiting, and sorry for the late, my wife has been (and is still) very illed, and I am facing lack of time to seriously work on the subject. For what I quickly reviewed, it seems ok, so let's go !

Once again, thanks for the tool and the time spent on it.

2023-12-17 20:05 UTC, merged